[package]
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"
name = "embassy-std-examples"
version = "0.1.0"

[dependencies]
embassy = { version = "0.1.0", path = "../../embassy", features = ["log", "std", "time"] }
embassy-net = { version = "0.1.0", path = "../../embassy-net", features=["std", "log", "medium-ethernet", "tcp", "dhcpv4"] }
smoltcp = { git = "https://github.com/smoltcp-rs/smoltcp", rev="e4241510337e095b9d21136c5f58b2eaa1b78479", default-features = false }

async-io = "1.3.1"
env_logger = "0.8.2"
futures = { version = "0.3.8", default-features = false, features = ["async-await"] }
log = "0.4.11"
nix = "0.21.0"
libc = "0.2.81"
clap = { version = "3.0.0-beta.2", features = ["derive"] }
rand_core   = { version = "0.6.0", features = ["std"] }
heapless            = { version = "0.7.1", default-features = false }
